spring.application.name=springboot-h2-db

# Nombre de la BD en memoria
spring.datasource.url=jdbc:h2:mem:mydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Consola de H2 para debuggear (acceso en /h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Ver las queries de Hibernate en la consola
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.thymeleaf.cache=false